KabelWeb/Controllers/KabelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KabelWeb.Controllers
{
    public class KabelController : Controller
    {
        //
        // GET: /Kabel/
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

    }
}

KabelWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    @RenderSection("JavaScriptIncludes", required: false)
</head>

<body>
    <div class="page">

        <div id="header">
            <div id="title">
                <h1>Kabellægning</h1>
            </div>

            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>

            <div id="menucontainer">

                <ul id="menu">
                    <li>@Html.ActionLink("Kabellægning", "Index", "Kabel")</li>
                    <li>@Html.ActionLink("Om", "About", "Home")</li>
                </ul>

            </div>
        </div>

        <div id="main">
            @RenderBody()
            <div id="footer">
            </div>
        </div>
    </div>
    
</body>
</html>

KabelWeb/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <b>@Context.User.Identity.Name</b>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}

KabelWeb/Views/Shared/_MobileLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8"> 
	<meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1"> 
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.0a3/jquery.mobile-1.0a3.min.css" />
    <script src="http://code.jquery.com/jquery-1.5.min.js" type="text/javascript"></script>
    <script src="http://code.jquery.com/mobile/1.0a3/jquery.mobile-1.0a3.min.js" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/geo/location.js")" type="text/javascript"></script>
</head>
<body>
        @RenderBody()
</body>
</html>